### PR TITLE
Fixed issue #53, #58, #46, and #61

### PR DESCRIPTION
**Pull request by brianslee**
Patched issue #53 so that the turnPanel is not covered when restarting the game. Looking at the code, fixing the bug entirely may require refactoring the GUI.

### CODE REVIEW

**Comment by brianslee** [comment]
Fixed Issue #58 so that players can add their names in the color menus. Note, GUI for second menu looks a bit ugly. Fixing up the GUI to look cleaner can be its own issue.

**Comment by brianslee** [comment]
Fixed issue #46 so that the color of the game board can be selected.

**Comment by brianslee** [comment]
Added more colors to the Board Color Select Menu.
Due to efforts exceeding initial projections, recommend ~200 points for task #46.

**Comment by brianslee** [comment]
Added a first attempt at a gradient button. It failed, but future programmers can use that as a reference.

**Comment by Peter-Master** [comment]
Fixed issue #61

**Comment by brianslee** [comment]
Javadoc has been removed.

**Pull request merged**
