### PR TITLE
fixes issue #29 and #57

### PR DESCRIPTION
**Pull request by brianslee**
Fixed issue #29 so that the coin toss function so that, when a new game is made, the player to go first is randomly selected for 100 points.
Note: the game informs the player(s) who gets to go first when a game is selected from the main menu. However, this feature does not appear when a game begins by clicking the restart button, as stated in issue #53

### CODE REVIEW

**Comment by brianslee** [comment]
Fixed issue #57 to improve the normal AI to detect 2-in-a-rows. However, this improvement was only made so that only AI 2-in-a-rows will be detected. The reason for this is because having the AI detect 2-in-a-rows for both the AI and the player makes the normal AI no different from the advanced AI.

**Comment by brianslee** [comment]
As an aside, I've stopped running into issue #50 and I'm not sure why.

**Comment by brianslee** [comment]
Also, figured out the problem for issue #53: When the board is redrawn, it's redrawn over the JPanel that holds the turn panel. So the turnPanel ends up hidden.

**Comment by Peter-Master** [comment]
fixes issue #54 -- users can now successfully use the "undo" button after a win

**Pull request merged**
